name: Remio Home Docker Image CI
on:
  push:
    branches: ['main']
    paths-ignore:
      - '**/*ignore*'

  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker Image
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile
          push: true
          tags: remio-home:latest,remio-home:${{github.sha}}
